blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
	url(r'^$', views.home, name="blog-home"),
	url(r'^category/(?P<category_id>\d+)/$', views.category_details, name="category-detail"),
	url(r'^post/(?P<post_id>\d+)/$', views.post_details, name="post-detail"),
	url(r'^add-comment/(?P<post_id>\d+)/$', views.add_comment, name="add_comment"),
]

mysite/urls.py
from django.conf import settings
import django.contrib.auth.views 
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name="login"),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('portfolio.urls', namespace='portfolio'), name="home"),
    url(r'^blog/', include('blog.urls', namespace='blog'), name="blog-home"),
    url(r'^dashboard/', include('site_engine.urls', namespace='site_engine'), name="dashboard"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Categorie(models.Model):
	category_name = models.CharField(max_length=200)
	created_on = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_on = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.category_name

class Post(models.Model):
	category = models.ForeignKey(Categorie, on_delete=models.CASCADE)
	post_title = models.CharField(max_length=200)
	post_content = models.TextField()
	post_image = models.FileField(blank=True, null=True)
	date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
	date_published = models.DateTimeField(auto_now_add=False, null=True)

	def publish(self):
		self.date_published = timezone.now()
		self.save()

	def approved_comments(self):
		return self.comments.filter(approved_comment=True)

	def __str__(self):
		return self.post_title

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	author = models.CharField(max_length=100)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	approved_comment = models.BooleanField(default=False)

	def approve(self):
		self.approved_comment = True
		self.save()

	def __str__(self):
		return self.text

blog/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Categorie, Post, Comment

# Create your views here.
def home(request):
	context = {
		'categories' : Categorie.objects.all(),
		'posts' : Post.objects.filter(date_published__isnull=False).order_by('-date_published'),
	}
	return render(request, "blog/home.html", context)

def category_details(request, category_id):
	context = {
		'category' : get_object_or_404(Categorie, pk=category_id),
		'categories' : Categorie.objects.all(),
		'posts' : Post.objects.filter(category=category_id, date_published__isnull=False).order_by('-date_published'),
	}
	return render(request, "blog/category_detail.html", context)

def post_details(request, post_id):
	context = {
		'post' : get_object_or_404(Post, pk=post_id),
		'categories' : Categorie.objects.all(),
	}
	return render(request, "blog/post_detail.html", context)

def add_comment(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	if request.method=="POST":
		author = request.POST['author']
		text = request.POST['text']
		comment = Comment(post=post, author=author, text=text)
		comment.save()
		messages.success(request, 'Success! Your comment has been submitted for approval!')
		return redirect('blog:post-detail', post_id = post_id)
	else:
		return redirect('blog:post-detail', post_id = post_id)

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static '/images/favicon.jpg' %}">
    <link rel="icon" href="{% static '/images/favicon-32.jpg' %}">
    <link rel="icon" href="{% static '/images/favicon-180.jpg' %}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static '/css/starter.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton|Bungee+Shade|Cabin|Cinzel|Cormorant|Courgette|Farsan|Fira+Sans+Condensed|Francois+One|Hammersmith+One|IM+Fell+English+SC|Josefin+Slab|Lobster+Two|Montserrat|Open+Sans|Open+Sans+Condensed:300|Orbitron|Oswald|Overpass|Overpass+Mono|Oxygen|PT+Sans|PT+Sans+Narrow|Poiret+One|Quicksand|Raleway|Righteous|Titillium+Web|Ubuntu|Yanone+Kaffeesatz" rel="stylesheet">
    <script src="https://use.fontawesome.com/223b6a0e4c.js"></script>
</head>
<body>
{% block content %}
{% endblock %}
	<footer id="contact" class=footer>
      <div class="container">
        <div class="col-md-4">
          <div class="page-header"><h4>Social</h4></div>
          <p><a href=""><i class="fa fa-github"></i> Github</a></p>
              <p><a href=""><i class="fa fa-facebook"></i> Facebook</a></p>
              <p><a href=""><i class="fa fa-twitter"></i> Twitter</a></p>
        </div>
        <div class="col-md-4">
          <div class="page-header"><h4>Find Me </h4></div>
                <p><i class="fa fa-globe"></i> 1436, Somewhere in Nairobi</p>
                <p><i class="fa fa-phone"></i> +254-7123456</p>
                <p><i class="fa fa-envelope"></i> piero@cyclonedevelopers.co.ke</p>
          </div>
        <div class="col-md-4">
        <div class="page-header"><h4>Talk To Me</h4></div>
          <form class="form-horizontal" role="form" method="POST" action="">
              <div class="form-group">
                <label class="footer-form-label" for="names">Name</label>
                <input type="text" name="name" class="form-control">
              </div>
              <div class="form-group">
                <label class="footer-form-label" for="email">Email</label>
                <input type="email" name="email" class="form-control">
              </div>
              <div class="form-group">
                <label class="footer-form-label" for="phone">Message</label>
                <textarea name="message" class="form-control" rows="6"></textarea>
              </div>
              <div class="col-md-offset-4">
                <button type="submit" class="btn btn-primary footer-form-submit" name="submit">SUBMIT</button>
              </div>
            </form>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends "base.html" %}

{% block title %}Blog - {{ category.category_name }}{% endblock %}

{% block content %}
<div class="container blog-home">
	<h2 class="page-header">Category: {{ category.category_name }}</h2>
	<div class="col-md-8">
		{% for post in posts %}
		<div class="blog-post-list">
			<div class="featured-img">
				<a href="{% url 'blog:post-detail' post.id %}">
				<img class="img-responsive" src="{{ post.post_image.url }}">
				</a>
			</div>
			<div class="page-header">
				<a href="{% url 'blog:post-detail' post.id %}">
				<h2>{{ post.post_title }}</h2>
				</a>
				<p>Published on: {{ post.date_created }}</p>
			</div>
			<p class="lead">{{ post.post_content | slice:"400" }}......</p>
			<p>Comments: {{ post.approved_comments.count }}</p>
			<a class="btn btn-primary" href="{% url 'blog:post-detail' post.id %}">Read more</a>
		</div>
		<hr>
		{% endfor %}
		
	</div>
	<div class="col-md-3 col-md-offset-1">
		<div class="archive-list">
			<div class="page-header">
				<h3>Categories</h3>
			</div>
			<ul class="list-unstyled">
			{% for category in categories %}
				<li class="category-list"><a href="{% url 'blog:category-detail' category.id %}">{{ category.category_name }}</a></li>
				<li role="separator" class="divider"></li>
			{% endfor %}
			</ul>
		</div>
		
	</div>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends "base.html" %}

{% block title %}Blog - Home{% endblock %}

{% block content %}
<div class="container blog-home">
	<div class="col-md-8">
		{% for post in posts %}
		<div class="blog-post-list">
			<div class="featured-img">
				<a href="{% url 'blog:post-detail' post.id %}">
				<img class="img-responsive" src="{{ post.post_image.url }}">
				</a>
			</div>
			<div class="page-header">
				<a href="{% url 'blog:post-detail' post.id %}">
				<h2>{{ post.post_title }}</h2>
				</a>
				<p>Published on: {{ post.date_created }}</p>
			</div>
			<p class="lead">{{ post.post_content | slice:"400" }}......</p>
			<p>Comments: {{ post.approved_comments.count }}</p>
			<a class="btn btn-primary" href="{% url 'blog:post-detail' post.id %}">Read more</a>
		</div>
		<hr>
		{% endfor %}
		
	</div>
	<div class="col-md-3 col-md-offset-1">
		<div class="archive-list">
			<div class="page-header">
				<h3>Categories</h3>
			</div>
			<ul class="list-unstyled">
			{% for category in categories %}
				<li class="category-list"><a href="{% url 'blog:category-detail' category.id %}">{{ category.category_name }}</a></li>
				<li role="separator" class="divider"></li>
			{% endfor %}
			</ul>
		</div>
		
	</div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}


{% block title %}Blog - Post {{ post.pk }}{% endblock %}

{% block content %}
<div class="container blog-home">
	<div class="col-md-8">
		{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags}}">{{ message }}</div>
		{% endfor %}
		{% endif %}
		<div class="blog-post-list">
			<div class="featured-img">
				<img class="img-responsive" src="{{ post.post_image.url }}">
			</div>
			<div class="page-header">
				<h2>{{ post.post_title }}</h2>
				<p>Published on: {{ post.date_created }}</p>
			</div>
			<p class="lead">{{ post.post_content|linebreaksbr }}</p>
		</div>
		<div class="post-comments">
			<h3>Comments</h3>
			{% for comment in post.comments.all %}
			{% if comment.approved_comment %}
			<div class="comment">
				<div class="comment-author"><strong>{{ comment.author}}</strong></div>
				<div class="comment-date">{{ comment.created_date }}</div>
				<p>{{ comment.text | linebreaks }}</p>
			</div>
			{% endif %}
			{% empty %}
			<h3>No comments here yet :(</h3>
			{% endfor %}

			<div class="add-comment">
				<p class="lead">Add comment</p>
				<form method="POST" action="{% url 'blog:add_comment' post.pk %}">{% csrf_token%}
					<label for="author">Author:</label>
					<input type="text" name="author" class="form-control" required>
					<label for="text">Comment:</label>
					<textarea class="form-control" rows="5" name="text" required></textarea>

					<button type="submit" class="btn btn-primary">Submit</button>
					<button type="reset" class="btn btb-danger">Cancel</button>
				</form>
			</div>
			
		</div>
	</div>
	<div class="col-md-3 col-md-offset-1">
		<div class="archive-list">
			<div class="page-header">
				<h3>Categories</h3>
			</div>
			<ul class="list-unstyled">
			{% for category in categories %}
				<li class="category-list"><a href="{% url 'blog:category-detail' category.id %}">{{ category.category_name }}</a></li>
				<li role="separator" class="divider"></li>
			{% endfor %}
			</ul>
		</div>
		
	</div>
</div>
{% endblock %}