blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
	url(r'^$', views.home, name="blog-home"),
	url(r'^category/(?P<category_id>\d+)/$', views.category_details, name="category-detail"),
	url(r'^post/(?P<post_id>\d+)/$', views.post_details, name="post-detail"),
	url(r'^add-comment/(?P<post_id>\d+)/$', views.add_comment, name="add_comment"),
]

mysite/urls.py
from django.conf import settings
import django.contrib.auth.views 
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name="login"),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('portfolio.urls', namespace='portfolio'), name="home"),
    url(r'^blog/', include('blog.urls', namespace='blog'), name="blog-home"),
    url(r'^dashboard/', include('site_engine.urls', namespace='site_engine'), name="dashboard"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_engine/urls.py
from django.conf.urls import url

from . import views

app_name = 'site_engine'

urlpatterns = [
	url(r'^$', views.dashboard, name="dashboard"),
	url(r'^projects/$', views.view_projects, name="view-projects"),
	url(r'^new-project/$', views.new_project, name="new-project"),
	url(r'^project-details/(?P<project_id>\d+)/$', views.project_details, name="project-details"),
	url(r'^edit-project/(?P<project_id>\d+)/$', views.edit_project, name="edit-project"),
	url(r'^delete-project/(?P<project_id>\d+)/$', views.delete_project, name="delete-project"),
	url(r'^blog-categories/$', views.view_blog_categories, name="blog-categories"),
	url(r'^new-blog-category/$', views.new_blog_category, name="new-blog-category"),
	url(r'^blog-category-details/(?P<category_id>\d+)/$', views.blog_category_details, name="blog-category-details"),
	url(r'^edit-blog-category/(?P<category_id>\d+)/$', views.edit_blog_category, name="edit-blog-category"),
	url(r'^delete-blog-category/(?P<category_id>\d+)/$', views.delete_blog_category, name="delete-blog-category"),
	url(r'^blog-posts/$', views.view_posts, name="view-posts"),
	url(r'^published-posts/$', views.published_blog_posts, name="published-posts"),
	url(r'^draft-posts/$', views.draft_blog_posts, name="draft-posts"),
	url(r'^post/(?P<post_id>\d+)/detail/$', views.post_details, name="post-details"),
	url(r'^new-post/$', views.new_blog_post, name="new-post"),
	url(r'^publish-post/(?P<post_id>\d+)/$', views.publish_blog_post, name="publish-post"),
	url(r'^edit-post/(?P<post_id>\d+)/$', views.update_blog_post, name="edit-post"),
	url(r'^delete-post/(?P<post_id>\d+)/$', views.delete_blog_post, name="delete-post"),
	url(r'^comments/$', views.posts_comments, name="view-comments"),
	url(r'^approve-comment/(?P<comment_id>\d+)/$', views.approve_comment, name="approve-comment"),
	url(r'^delete-comment/(?P<comment_id>\d+)/$', views.delete_comment, name="delete-comment"),
	url(r'^users/$', views.view_users, name="users"),
	url(r'^new-user/$', views.new_user, name="new-user"),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Categorie(models.Model):
	category_name = models.CharField(max_length=200)
	created_on = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated_on = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.category_name

class Post(models.Model):
	category = models.ForeignKey(Categorie, on_delete=models.CASCADE)
	post_title = models.CharField(max_length=200)
	post_content = models.TextField()
	post_image = models.FileField(blank=True, null=True)
	date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
	date_published = models.DateTimeField(auto_now_add=False, null=True)

	def publish(self):
		self.date_published = timezone.now()
		self.save()

	def approved_comments(self):
		return self.comments.filter(approved_comment=True)

	def __str__(self):
		return self.post_title

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	author = models.CharField(max_length=100)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	approved_comment = models.BooleanField(default=False)

	def approve(self):
		self.approved_comment = True
		self.save()

	def __str__(self):
		return self.text

site_engine/models.py
from django.db import models

# Create your models here.

site_engine/forms.py
from django import forms
from django.contrib.auth.models import User

from portfolio.models import Project
from blog.models import Categorie, Post

class ProjectForms(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['project_name', 'project_description', 'project_image', 'project_link']

class CategoryForms(forms.ModelForm):
	class Meta:
		model = Categorie
		fields = ['category_name']

class BlogPostForms(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('category', 'post_title', 'post_content', 'post_image')

class UserForms(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name','username', 'email', 'password')

site_engine/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect, get_object_or_404
from portfolio.models import Project
from blog.models import Categorie, Post, Comment
from django.contrib.auth.models import User
from .forms import ProjectForms, CategoryForms, BlogPostForms, UserForms

# Create your views here.
# Function to view the home page dor site_engine app
@login_required
def dashboard(request):
	posts = Post.objects.all()
	projects = Project.objects.all()
	comments = Comment.objects.all()
	context = {
		'posts' : posts,
		'projects' : projects,
		'comments' : comments
	}
	return render(request, "site_engine/dashboard.html", context)

# BEGIN PORTFOLIO CRUD FUNCTIONS
# Fetches all projects from database
@login_required
def view_projects(request):
	context = {
		'projects' : Project.objects.all(),
	}
	return render(request, "site_engine/projects.html", context)

# Adds a new project to the database and launches form template for the project details
@login_required
def new_project(request):
	if request.method=="POST":

		form = ProjectForms(request.POST, request.FILES)
		if form.is_valid():
			form.save(commit=False)
			form.save()
			return redirect("site_engine:view-projects")
	else:
		context = {
			'form' : ProjectForms()
		}
	return render(request, "site_engine/new_project.html", context)

# Fetches details of a particular project from the database 
@login_required
def project_details(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	context = {
		'project' : project,
	}
	return render(request, "site_engine/project_details.html", context)

# Fetches data of a particular project for editing and posts the updated data
@login_required
def edit_project(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	if request.method=="POST":
		form = ProjectForms(request.POST, request.FILES, instance=project)
		if form.is_valid():
			form.save()
			return redirect("site_engine:project-details", project_id=project_id)
	else:
		form = ProjectForms(instance=project)
	return render(request, "site_engine/edit_project.html", {'form':form})

# Deletes a particular project from the database
@login_required
def delete_project(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	project.delete()
	return redirect("site_engine:view-projects")

# END PORTFOLIO FUNCTIONS

# BEGIN BLOG CRUD FUNCTIONS
# Fetches all blog categories from teh database
@login_required
def view_blog_categories(request):
	context = {
		'categories' : Categorie.objects.all(),
	}
	return render(request, "site_engine/blog_categories.html", context)

# Adds a new blog category to the database and launches the form for the category details
@login_required
def new_blog_category(request):
	if request.method=="POST":

		form = CategoryForms(request.POST)
		if form.is_valid():
			form.save()
			return redirect('site_engine:blog-categories')
	else:

		context = {
			'form' : CategoryForms(),
		}
	return render(request, "site_engine/new_blog_category.html", context)

# Fetches details of a particular blog category for editing and launches the form  for the same
@login_required
def edit_blog_category(request, category_id):
	category = get_object_or_404(Categorie, pk=category_id)
	if request.method=="POST":
		form = CategoryForms(request.POST, instance=category)
		if form.is_valid():
			form.save()
			return redirect("site_engine:blog-categories")
	else:
		context = {
			'form' : CategoryForms(instance=category)
		}
	return render(request, "site_engine/edit_blog_category.html", context)

# Fetches a particular blog category and its details from the database
@login_required
def blog_category_details(request, category_id):
	category = get_object_or_404(Categorie, pk=category_id)
	context = {
		'category' : category,
	}
	return render(request, "site_engine/blog_category_details.html", context)

@login_required
def delete_blog_category(request, category_id):
	category = get_object_or_404(Categorie, pk=category_id)
	category.delete()
	return redirect("site_engine:blog-categories")

# Fetches all the blog posts in the database
@login_required
def view_posts(request):
	context = {
		'posts' : Post.objects.all().order_by('-date_created'),
	}
	return render(request, "site_engine/blog_posts.html", context)

# Function to get published blogs only
@login_required
def published_blog_posts(request):
	context = {
		'posts' : Post.objects.filter(date_published__isnull=False).order_by('-date_published'),
	}
	return render(request, "site_engine/blog_posts.html", context)

# Function to get draft blogs only
@login_required
def draft_blog_posts(request):
	context = {
		'posts' : Post.objects.filter(date_published__isnull=True).order_by('-date_created'),
	}
	return render(request, "site_engine/blog_posts.html", context)

# Function to get blog post details
@login_required
def post_details(request, post_id):
	context = {
		'post' : get_object_or_404(Post, pk=post_id)
	}
	return render(request, "site_engine/post_details.html", context)

# Function to publish a draft post
@login_required
def publish_blog_post(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	post.publish()
	return redirect("site_engine:post-details", post_id=post_id)

@login_required
def new_blog_post(request):
	if request.method=="POST":
		form = BlogPostForms(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect("site_engine:view-posts")
	else:
		context = {
			'form' : BlogPostForms(),
		}
	return render(request, "site_engine/new_blog_post.html", context)

@login_required
def update_blog_post(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	if request.method=="POST":
		form = BlogPostForms(request.POST, request.FILES, instance=post)
		if form.is_valid():
			form.save()
			return redirect("site_engine:post-details", post_id=post_id)
	else:
		context = {
			'form' : BlogPostForms(instance=post),
			'post' : post,
		}
	return render(request, "site_engine/edit_blog_post.html", context)

@login_required
def delete_blog_post(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	post.delete()
	return redirect("site_engine:view-posts")

@login_required
def posts_comments(request):
	comments = Comment.objects.filter(approved_comment=False)
	context = {
		'comments' : comments,
	}
	return render(request, 'site_engine/post-comments.html',  context)

@login_required
def approve_comment(request, comment_id):
	comment = get_object_or_404(Comment, pk=comment_id)
	comment.approved_comment = True
	comment.save()
	return redirect('site_engine:view-comments')

@login_required
def delete_comment(request, comment_id):
	comment = get_object_or_404(Comment, pk=comment_id)
	comment.delete()
	return redirect('site_engine:view-comments')

# END BLOG FUNCTIONS

# START USERS FUNCTIONS
@login_required
def view_users(request):
	context = {
		'users' : User.objects.all(),
	}
	return render(request, "site_engine/users.html", context)

@login_required
def new_user(request):
	if request.method=="POST":
		form = UserForms(request.POST)
		if form.is_valid():
			form.save()
			return redirect("site_engine:users")
	else:
		context = {
			'form' : UserForms(),
		}
	return render(request, "site_engine/new_user.html", context)

site_engine/templates/site_engine/blog_categories.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Blog Categories{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
  <a class="btn btn-primary pull-right" href="{% url 'site_engine:new-blog-category' %}"><i class="fa fa-plus"></i> Category</a>
  <h2 class="sub-header">Existent Categories</h2>
  {% for category in categories %}
  <a href="{% url 'site_engine:blog-category-details' category.id %}">
  <div class="col-md-3 blog-category">
  <h1>{{ category.category_name }}</h1>
  <p><strong>Created on:</strong> {{ category.created_on }}</p>
  </div>
  </a>
  {% endfor %}
  
</div>
{% endblock %}

site_engine/templates/site_engine/blog_category_details.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Category Details{% endblock %}

{% block content %}
	<div class="col-md-9 col-md-offset-2 main">
		<a class="btn btn-primary pull-right" href=""><i class="fa fa-plus"></i> Post</a>
		<h2 class="sub-header"><strong>Category:</strong> {{ category.category_name }}</h2>
		<h2><strong>Date added:</strong> <small>{{ category.created_on }}</small></h2>
		<a class="btn btn-success" href="{% url 'site_engine:edit-blog-category' category.id %}"><i class="fa fa-edit"></i> Edit</a>
		<a class="btn btn-danger" href="{% url 'site_engine:delete-blog-category' category.id %}"><i class="fa fa-trash-o"></i> Delete</a>
		<hr>
		{% for post in category.post_set.all %}
		<div class="col-md-3">
			<img class="img-responsive" src="{{ post.post_image.url }}">
			<h3>{{ post.post_title }}</h3>
			<p>{{ post.post_content|slice:"150" }}</p>
			<a class="btn btn-warning" href="{% url 'site_engine:post-details' post.id %}">More Details</a>
		</div>
		{% endfor %}
	</div>
{% endblock %}

site_engine/templates/site_engine/dashboard.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Home{% endblock %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header">Dashboard</h1>

  <div class="row placeholders">
    <div class="col-md-4">
      <div class="well red-well">
        <div class="stat-no">{{ projects.count }}</div>
        <div class="stat-icon">
          <i class="fa fa-folder"></i>
          <p>Projects</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="well blue-well">
        <div class="stat-no">{{ posts.count }}</div>
        <div class="stat-icon">
          <i class="fa fa-edit"></i>
          <p>Posts</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="well green-well">
        <div class="stat-no">{{ comments.count }}</div>
        <div class="stat-icon">
          <i class="fa fa-comment"></i>
          <p>Comments</p>
        </div>
      </div>
    </div>
  </div>

  <h2 class="sub-header">Section title</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Header</th>
          <th>Header</th>
          <th>Header</th>
          <th>Header</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1,001</td>
          <td>Lorem</td>
          <td>ipsum</td>
          <td>dolor</td>
          <td>sit</td>
        </tr>
        <tr>
          <td>1,002</td>
          <td>amet</td>
          <td>consectetur</td>
          <td>adipiscing</td>
          <td>elit</td>
        </tr>
        <tr>
          <td>1,003</td>
          <td>Integer</td>
          <td>nec</td>
          <td>odio</td>
          <td>Praesent</td>
        </tr>
        <tr>
          <td>1,003</td>
          <td>libero</td>
          <td>Sed</td>
          <td>cursus</td>
          <td>ante</td>
        </tr>
        <tr>
          <td>1,004</td>
          <td>dapibus</td>
          <td>diam</td>
          <td>Sed</td>
          <td>nisi</td>
        </tr>
        <tr>
          <td>1,005</td>
          <td>Nulla</td>
          <td>quis</td>
          <td>sem</td>
          <td>at</td>
        </tr>
        <tr>
          <td>1,006</td>
          <td>nibh</td>
          <td>elementum</td>
          <td>imperdiet</td>
          <td>Duis</td>
        </tr>
        <tr>
          <td>1,007</td>
          <td>sagittis</td>
          <td>ipsum</td>
          <td>Praesent</td>
          <td>mauris</td>
        </tr>
        <tr>
          <td>1,008</td>
          <td>Fusce</td>
          <td>nec</td>
          <td>tellus</td>
          <td>sed</td>
        </tr>
        <tr>
          <td>1,009</td>
          <td>augue</td>
          <td>semper</td>
          <td>porta</td>
          <td>Mauris</td>
        </tr>
        <tr>
          <td>1,010</td>
          <td>massa</td>
          <td>Vestibulum</td>
          <td>lacinia</td>
          <td>arcu</td>
        </tr>
        <tr>
          <td>1,011</td>
          <td>eget</td>
          <td>nulla</td>
          <td>Class</td>
          <td>aptent</td>
        </tr>
        <tr>
          <td>1,012</td>
          <td>taciti</td>
          <td>sociosqu</td>
          <td>ad</td>
          <td>litora</td>
        </tr>
        <tr>
          <td>1,013</td>
          <td>torquent</td>
          <td>per</td>
          <td>conubia</td>
          <td>nostra</td>
        </tr>
        <tr>
          <td>1,014</td>
          <td>per</td>
          <td>inceptos</td>
          <td>himenaeos</td>
          <td>Curabitur</td>
        </tr>
        <tr>
          <td>1,015</td>
          <td>sodales</td>
          <td>ligula</td>
          <td>in</td>
          <td>libero</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

site_engine/templates/site_engine/edit_blog_category.html
{% extends "site_engine/base.html" %}
{% load crispy_forms_tags %}

{% block title %} Dashboard - Edit Blog Category{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
  <h2 class="sub-header">Edit Category</h2>
  <div class="col-md-offset-2 col-md-4">
  	<form role="form" class="form-horizontal" action="" method="POST">{% csrf_token %}
  		{{ form|crispy}}
  		<button type="reset" class="btn btn-danger">Cancel</button>
  		<input type="submit" name="submit" class="btn btn-primary" value="Submit">
  	</form>
  </div>
  
</div>
{% endblock %}

site_engine/templates/site_engine/edit_blog_post.html
{% extends "site_engine/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Blog Post - {{ post.id }}{% endblock %}

{% block content %}
<div class="col-md-offset-2 col-md-9 main">
	<h2 class="sub-header">{{ post.post_title }} Details</h2>
	<hr>
	<div class="col-md-offset-2 col-md-8">
		<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form | crispy }}
			<a href="{% url 'site_engine:post-details' post.id %}"><button type="button" class="btn btn-danger">Cancel</button></a>
			<button type="submit" class="btn btn-success">Submit</button>
		</form>
	</div>
</div>
{% endblock %}

site_engine/templates/site_engine/edit_project.html
{% extends "site_engine/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Project{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
  <h2 class="sub-header">Edit Project</h2>
  <div class="col-md-offset-2 col-md-4">
  	<form role="form" class="form-horizontal" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
  		{{ form|crispy}}
  		<button type="reset" class="btn btn-danger">Cancel</button>
  		<input type="submit" name="submit" class="btn btn-primary" value="Submit">
  	</form>
  </div>
  
</div>
{% endblock %}

site_engine/templates/site_engine/new_blog_category.html
{% extends "site_engine/base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Blog Category{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
  <h2 class="sub-header">Add New Category</h2>
  <div class="col-md-offset-2 col-md-4">
  	<form role="form" class="form-horizontal" action="" method="POST">{% csrf_token %}
  		{{ form|crispy}}
  		<button type="reset" class="btn btn-danger">Cancel</button>
  		<input type="submit" name="submit" class="btn btn-primary" value="Submit">
  	</form>
  </div>
  
</div>
{% endblock %}

site_engine/templates/site_engine/new_blog_post.html
{% extends "site_engine/base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Blog Post{% endblock %}

{% block content %}
<div class="col-md-offset-2 col-md-9 main">
	<h2 class="sub-header">New Blog Post</h2>
	<hr>
	<div class="col-md-offset-2 col-md-8">
		<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form | crispy }}
			<button type="reset" class="btn btn-danger">Cancel</button>
			<button type="submit" class="btn btn-success">Submit</button>
		</form>
	</div>
</div>
{% endblock %}

site_engine/templates/site_engine/new_user.html
{% extends "site_engine/base.html" %}
{% load crispy_forms_tags %}

{% block title %}New User{% endblock %}

{% block content %}
<div class="col-md-offset-2 col-md-9 main">
	<h2 class="sub-header">Add New User</h2>
	<div class="col-md-offset-2 col-md-6">
		<form class="form-horizontal" method="POST" action="">{% csrf_token %}
			{{ form|crispy }}
			<div class="col-md-offset-3">
				<button class="btn btn-danger" type="reset">Cancel</button>
				<button class="btn btn-success" type="submit" name="submit">Submit</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}

site_engine/templates/site_engine/post-comments.html
{% extends "site_engine/base.html" %}

{% block title %}Post Comments{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
	<h3 class="page-header">Comments pending approval</h3>
	<div class="comment-approval">
		{% for comment in comments %}
		<div class="comment">
			<h4>Post: <span>{{ comment.post }}</span></h4>
			<div class="author"><strong>{{ comment.author }}</strong></div>
			<div class="comment-date">{{ comment.created_date }}</div>
			<p>{{ comment.text | linebreaks }}</p>
			<a class="btn btn-primary" href="{% url 'site_engine:approve-comment' comment.id %}">Approve</a>
			<a class="btn btn-danger" href="{% url 'site_engine:delete-comment' comment.id %}">Delete</a>
		</div>
		{% empty %}
		<h4>No comments pending approval :)!</h4>
		{% endfor %}
	</div>
</div>
{% endblock %}

site_engine/templates/site_engine/post_details.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Post {{ post.id }}{% endblock %}

{% block content %}
	<div class="col-md-9 col-md-offset-2 main">
		<h2 class="sub-header">{{ post.post_title }}</h2>
		<p><strong>Category:</strong> {{ post.category }}</p>
		<hr>
		<div>
		{% if post.post_image %}
			<img src="{{ post.post_image.url }}" class="img-responsive center-block">
			{% endif %}
			<p class="lead">{{ post.post_content|linebreaksbr }}</p>
		</div>
		{% if not post.date_published %}
		<a class="btn btn-primary" href="{% url 'site_engine:publish-post' post.id %}"><i class="fa fa-pencil-square"></i> Publish</a>
		{% endif %}
		<a class="btn btn-success" href="{% url 'site_engine:edit-post' post.id %}"><i class="fa fa-edit"></i> Edit</a>
		<a class="btn btn-danger" href="{% url 'site_engine:delete-post' post.id %}" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</a>
	</div>
{% endblock %}

site_engine/templates/site_engine/project_details.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Project {{ project.id}}{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
  <h2 class="sub-header text-center">{{ project.project_name }}</h2>
  <div class="col-md-offset-2 col-md-9">
  	<img class="img-responsive" src="{{ project.project_image.url }}">
  	<div class="project-description">
  		<p>{{ project.project_description|linebreaksbr }}</p>
  	</div>
    <i class="fa fa-link"></i> <a href="{{ project.project_link }}">{{ project.project_link}}</a>
    <hr>
    <div class="pull-right">
      <a class="btn btn-success" href="{% url 'site_engine:edit-project' project.id %}"><i class="fa fa-edit"></i> Edit</a>
      <a class="btn btn-danger" href="{% url 'site_engine:delete-project' project.id %}" onclick="return confirm('Are you sure?');"><i class="fa fa-trash-o"></i> Delete</a>
    </div>
  </div>
  
</div>
{% endblock %}

site_engine/templates/site_engine/projects.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Projects{% endblock %}

{% block content %}
<div class="col-md-9 col-md-offset-2 main">
  <a class="btn btn-primary pull-right" href="{% url 'site_engine:new-project' %}"><i class="fa fa-plus"></i> Project</a>
  <h2 class="sub-header">Uploaded Projects</h2>
  {% for project in projects %}
  <div class="col-md-3 project">
  	<img class="img-responsive" src="{{ project.project_image.url }}">
  	<div class="project-description">
  		<h3>{{ project.project_name }}</h3>
  		<p>{{ project.project_description|slice:"120"}}....</p>
  	</div>
    <a class="btn btn-warning center-block" href="{% url 'site_engine:project-details' project.id %}">Details</a>
  </div>
  {% endfor %}
  
</div>
{% endblock %}

site_engine/templates/site_engine/users.html
{% extends "site_engine/base.html" %}

{% block title %}Dashboard - Users{% endblock %}

{% block content %}
<div class="col-md-offset-2 col-md-9 main">
	<a class="btn btn-primary pull-right" href="{% url 'site_engine:new-user' %}"><i class="fa fa-plus"></i> User</a>
	<h2 class="sub-header">Registered Users</h2>
	<table class="table table-striped table-responsive">
		<thead>
			<th>Name</th>
			<th>Username</th>
			<th>Email</th>
			<th>Usertype</th>
		</thead>
		<tbody>
			{% for user in users %}
			<tr>
				<td>{{ user.first_name }} {{ user.last_name }}</td>
				<td>{{ user.username }}</td>
				<td>{{ user.email }}</td>
				<td>{{ user.status }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}