blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
	url(r'^$', views.home, name="blog-home"),
	url(r'^category/(?P<category_id>\d+)/$', views.category_details, name="category-detail"),
	url(r'^post/(?P<post_id>\d+)/$', views.post_details, name="post-detail"),
	url(r'^add-comment/(?P<post_id>\d+)/$', views.add_comment, name="add_comment"),
]

mysite/urls.py
from django.conf import settings
import django.contrib.auth.views 
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name="login"),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('portfolio.urls', namespace='portfolio'), name="home"),
    url(r'^blog/', include('blog.urls', namespace='blog'), name="blog-home"),
    url(r'^dashboard/', include('site_engine.urls', namespace='site_engine'), name="dashboard"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url

from . import views

app_name = 'portfolio'

urlpatterns = [
	url(r'^$', views.index, name="home"),
	url(r'^project/(?P<project_id>\d+)/$', views.project_details, name="project-details"),
	url(r'^send-email/$', views.send_email, name="send_email"),
	url(r'^facebook/$', views.fb_profile, name="facebook"),
	url(r'twitter/$', views.twitter_profile, name="twitter"),
	url(r'^github/$', views.github_profile, name="github"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static '/images/favicon.jpg' %}">
    <link rel="icon" href="{% static '/images/favicon-32.jpg' %}">
    <link rel="icon" href="{% static '/images/favicon-180.jpg' %}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static '/css/blog.css' %}" rel="stylesheet">
    <link href="{% static '/css/starter.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton|Bungee+Shade|Cabin|Cinzel|Cormorant|Courgette|Farsan|Fira+Sans+Condensed|Francois+One|Hammersmith+One|IM+Fell+English+SC|Josefin+Slab|Lobster+Two|Montserrat|Open+Sans|Open+Sans+Condensed:300|Orbitron|Oswald|Overpass|Overpass+Mono|Oxygen|PT+Sans|PT+Sans+Narrow|Poiret+One|Quicksand|Raleway|Righteous|Titillium+Web|Ubuntu|Yanone+Kaffeesatz" rel="stylesheet">
    <script src="https://use.fontawesome.com/223b6a0e4c.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: black;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'portfolio:home' %}" style="color: white;">Piero Muguna</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav nav-list-one">
            <li><a href="{% url 'portfolio:home' %}">Home</a></li>
            <li><a href="{% url 'portfolio:home' %}#about">About</a></li>
            <li><a href="{% url 'portfolio:home' %}#projects">Projects</a></li>
            <li><a href="{% url 'blog:blog-home' %}">Blog</a></li>
            <li><a href="{% url 'portfolio:home' %}#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% if success %}
    <div class="alert alert-success">
      <strong>Success!!</strong> Message successfully sent
    </div>
    {% endif %}

   {% block content %}
   {% endblock %}
   <footer id="contact" class=footer>
      <div class="container">
        <div class="col-md-4">
          <div class="page-header"><h4>Social</h4></div>
          <p><a href="{% url 'portfolio:github' %}" target="_blank"><i class="fa fa-github"></i> Github</a></p>
              <p><a href="{% url 'portfolio:facebook' %}" target="_blank"><i class="fa fa-facebook"></i> Facebook</a></p>
              <p><a href="{% url 'portfolio:twitter' %}" target="_blank"><i class="fa fa-twitter"></i> Twitter</a></p>
        </div>
        <div class="col-md-4">
          <div class="page-header"><h4>Find Me </h4></div>
                <p><i class="fa fa-globe"></i> 1436, Somewhere in Nairobi</p>
                <p><i class="fa fa-phone"></i> +254-7123456</p>
                <p><i class="fa fa-envelope"></i> piero@cyclonedevelopers.co.ke</p>
                {% if user.is_authenticated %}
                <a href="{% url 'site_engine:dashboard' %}" target="_blank" style="color: white; text-decoration: none;">{{ user.username }}</a>
                {% endif %}
          </div>
        <div class="col-md-4">
        <div class="page-header"><h4>Talk To Me</h4></div>
          <form class="form-horizontal" role="form" method="POST" action="{% url 'portfolio:send_email' %}">{% csrf_token%}
              <div class="form-group">
                <label class="footer-form-label" for="names">Name</label>
                <input type="text" name="name" class="form-control">
              </div>
              <div class="form-group">
                <label class="footer-form-label" for="email">Email</label>
                <input type="email" name="email" class="form-control">
              </div>
              <div class="form-group">
                <label class="footer-form-label" for="phone">Message</label>
                <textarea name="message" class="form-control" rows="6"></textarea>
              </div>
              <div class="col-md-offset-4">
                <button type="submit" class="btn btn-primary footer-form-submit" name="submit">SUBMIT</button>
              </div>
            </form>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}PieroMuguna - Home{% endblock %}

{% block content %}
<div class="container-fluid hero-section">
	<div class="hero-text">
		<h1>Hello World!</h1>
	</div>
</div>
<div id="about" class="container auto-b">
	<div class="page-header">
		<h1 class="text-center">Who Am I?</h1>
	</div>
	<img class="img-responsive img-circle center-block bio-image" src="{% static '/images/me.png' %}">
	<p class="lead">Hi there, thanks for taking time to drop by. I am Piero, a passionate web development enthusiast who cares deeply about beautiful design and elegant code. My strengths are in complete end-end management of a new website development project.</p>
	<p class="lead">I'm on a journey to programming mastery, my main focus is Python's framework Django and PHP. I am all about coming up with state of art Django and PHP web applications. Join me as I work towards becoming a developer sensei!</p>
</div>
<div id="projects" class="container-fluid projects">
	<div class="container">
		<div class="page-header">
			<h1 class="text-center">My Projects</h1>
		</div>
		{% for project in projects %}
		<div class="col-md-4 project">
			<a href="{% url 'portfolio:project-details' project.id %}">
			<img class="img-responsive" src="{{ project.project_image.url }}">
			</a>
			<div class="project-description">
				<a href="{% url 'portfolio:project-details' project.id %}">
				<h3 class="page-header">{{ project.project_name }}</h3>
				</a>
				<p>{{ project.project_description | slice:"100" }}...</p>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}